steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install', '--frozen-lockfile', '--production=false']
- name: 'node'
  entrypoint: 'yarn'
  args: ['build']
- name: 'zenika/alpine-chrome:with-node' 
  entrypoint: 'yarn'
  args: ['test']
options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
artifacts:
  npmPackages:
  - repository: 'https://us-central1-npm.pkg.dev/safevalues-cicd/svtestrelease'
    packagePath: '.'
