steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install', '--frozen-lockfile', '--production=false']
- name: 'node'
  entrypoint: 'yarn'
  args: ['build']
- name: 'node'
  entrypoint: 'bash'
  args: ['-c', 'echo "//registry.npmjs.org/:_authToken=$$NODE_AUTH_TOKEN" > ~/.npmrc']
  secretEnv: ['NODE_AUTH_TOKEN']
- name: 'node'
  entrypoint: 'npm'
  args: ['publish', '--provenance']
availableSecrets:
  secretManager:
  - versionName: projects/457115741181/secrets/NPM_AUTH_TOKEN/versions/1
    env: 'NODE_AUTH_TOKEN'
options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
artifacts:
  npmPackages:
  - repository: 'https://us-central1-npm.pkg.dev/safevalues-cicd/svtestrelease'
    packagePath: '.'
