steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install', '--frozen-lockfile']
- name: 'node'
  entrypoint: 'yarn'
  args: ['build']
- name: 'ubuntu' 
  entrypoint: 'yarn'
  args: ['test']
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  npmPackages:
  - repository: 'https://svtestrelease-npm.pkg.dev/safevalues-cicd/svtestrelease'
    packagePath: '.'
